server:
    port: 8082
spring:
    application:
        name: HOTEL_SERVICE 
    datasource:
        url: jdbc:postgresql://localhost:5432/microservice
        username: postgres
        password: password
        driver-class-name: org.postgresql.Driver
    config:
        import: configserver:http://localhost:8085
    # profiles:
    #     active: prod
    
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        open-in-view: false
        # properties:
            # hibernate:
                # dialect: org.hibernate.dialect.PostgreSQLDialect
# eureka:
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/
#   instance:
#     preferIpAddress: true # Optional, for preferring IP address in registration